### ISSUE TITLE
Address in Order View

### ISSUE THREAD

**Issue by sociorent** [sociorent/production#17]
Please include the Address of the customer in the View Order page and also arrange the books ordered in lines.

**Comment by thamizh2k7** [comment]
Fixes this issue #17 https://github.com/sociorent/production/commit/ec5331dd70258233835c1bb26db1823eb6dae831

**Comment by sociorent** [comment]
Please include the following details in the books details too:

Title -> Author -> Publisher -> ISBN -> Price -> Rental Amount

**Comment by thamizh2k7** [comment]
this will fix the Title -> Author -> Publisher -> ISBN -> Price -> Rental Amount
https://github.com/sociorent/production/commit/aac876bff1901d0e6e66baccb4c590ee8a435e67
