### ISSUE TITLE
Some Users not have college in their profile.

### ISSUE THREAD

**Issue by pSenthil202** [sociorent/production#19]
Reproduce

  Login Admin> users> and check the list , 638 users found without college

Expected

   College should be compulsory input.

Solution 

```
Redirect all the controller to welcome page , if mobile , college stream are not present.
Before file in application controller will solve this.
```

**Comment by thamizh2k7** [comment]
fixes the issue: #19 https://github.com/sociorent/production/commit/fe278fa66ab7c1766352fb041394665e8e7fd290
