### ISSUE TITLE
Add more columns to shipped and unshipped items in admin

### ISSUE THREAD

**Issue by pSenthil202** [sociorent/production#22]
Go to Admin > Shipping

We have unshipped , shipped, cancelled items list 

Please add all the order details to this list.

**Comment by sociorent** [comment]
Shipped & Unshipped Items does not show any item. Though we have unshipped items for today, it still shows No items.

**Comment by marudhupandiyang** [comment]
@sociorent can u conform  this again. There must me items under shipped and un-shipped items which will get affected only for new entries and not for old entries. If still there is a bug, please attach a screenshot and some details
