### ISSUE TITLE
Change Citrus pay to production  and remove Gharpay

### ISSUE THREAD

**Issue by pSenthil202** [sociorent/production#26]
Change the Citrus pay API keys to production mode.

**Comment by thamizh2k7** [comment]
Citrus pay live mode is in https://github.com/sociorent/production/commit/98688b5e9f70f581a65290ec42c751d581e0e5d2

removing gharpay  not done yet

**Comment by thamizh2k7** [comment]
Removed Gharpay #26 fixes :https://github.com/sociorent/production/commit/8788670dd487573d51fb6ae009a3f1402a17c89b

**Comment by sociorent** [comment]
Citrus pay does not work. It throws an error as the transaction ID is missing.

**Comment by thamizh2k7** [comment]
This commit will fix citrus pay error 
https://github.com/sociorent/production/commit/fc685ce93287464d31625976403527faaff866fa
