### ISSUE TITLE
Multiple issues User welcome 

### ISSUE THREAD

**Issue by pSenthil202** [sociorent/production#5]
Reproduce:

1) Signup with new email
2) You will be taken to welcome form for to enter mobile number and college
3) Mobile number validation just shown but not stops user , if i type existing mobile number , it say mobile alreay taken but it redirects users to go in.
4) College list should be auto suggest , not chosen.

Expected result.
1) Proper validation
2) Auto suggest instead of chosen

**Comment by thamizh2k7** [comment]
Fixes #5 https://github.com/sociorent/production/commit/6ecbf14a4cd557d7efff006079916c03fe64ef6c
