### ISSUE TITLE
Add new book form Upload for image

### ISSUE THREAD

**Issue by pSenthil202** [sociorent/production#6]
Reproduce :

1) Login to Admin > Books > New Book
2) All books have images, but there is not upload button for book image in and edit form.

Expected 

1) All image file types should have upload file button across admin panel.

**Comment by thamizh2k7** [comment]
Fixes the issue #6 https://github.com/sociorent/production/commit/4385620e9ea1cb385e2073e1b148eb1384ac8fe2
