### ISSUE TITLE
Big Upload image in new listing form for new items

### ISSUE THREAD

**Issue by balachandar2k12** [sociorent/production#80]
1. The Upload icon in new listing form should cover the whole image and be visibly big.

**Comment by balachandar2k12** [comment]
uploaded images should be visible in big thumbnail....

URL : http://awesomescreenshot.com/011z7po41

**Comment by marudhupandiyang** [comment]
Plz change the upload image to something tat suites the site design.

http://awesomescreenshot.com/011z7po41

**Comment by pSenthil202** [comment]
Vibhoo you can try with the attachment.
![Upload Pic](https://f.cloud.github.com/assets/639130/198380/ac3308d2-8059-11e2-8e70-d5c262265422.png)

**Comment by vibhoo** [comment]
Marudhu please check image upload form

**Comment by balachandar2k12** [comment]
how do i view the Uploaded image view ..
if i am clicking the image it should be showed in the uploaded place
