### ISSUE TITLE
in compose message if user is not available, no intimation is displayed

### ISSUE THREAD

**Issue by balachandar2k12** [sociorent/production#94]
1.  compose message if user is not available, no intimation is displayed
2. after retry the compose message  old texts not cleared....

URL :   http://awesomescreenshot.com/0b3z7ed88

**Comment by marudhupandiyang** [comment]
Fixed #94  in 8262409a5a84983061b57bfca688631fa89752f3

**Comment by balachandar2k12** [comment]
remove the notification  if cancel the compose message
